name: Docker Image To Registry

on:
  workflow_dispatch:

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      -
        name: Build with Gradle
        run: ./gradlew build
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/386,linux/amd64
          push: true
          tags: |
            ghcr.io/augur/five-letters/fl-backend:latest
            ghcr.io/augur/five-letters/fl-backend:20.12.1.test
